FROM alpine
RUN (export http_proxy=http://10.158.100.6:8080;https_proxy=http://10.158.100.6:8080;apk update)
RUN (export http_proxy=http://10.158.100.6:8080;https_proxy=http://10.158.100.6:8080;apk add --update py-pip)
RUN (export http_proxy=http://10.158.100.6:8080;https_proxy=http://10.158.100.6:8080;pip install flask)
