apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world-deployment
  labels:
    app: flask-hello-world
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-hello-world
  template:
    metadata:
      labels:
        app: flask-hello-world
    spec:
      containers:
      - name: flask-hello-world-container
        image: sunilkhokalay/hello-world-flask
        ports:
        - containerPort: 5050
