--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: redis-app
  name: redis-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: redis-app
  template: 
    metadata: 
      labels: 
        app: redis-app
    spec: 
      containers: 
        - 
          image: redis
          name: redis-container
          ports: 
            - 
              containerPort: 6379
          volumeMounts: 
            - 
              mountPath: /data
              name: redis-pv-storage
      volumes: 
        - 
          name: redis-pv-storage
          persistentVolumeClaim: 
            claimName: redis-pv-claim

