apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-deployment
  labels:
    app: notes-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-container
        image: sunilkhokalay/notes:1.1.1
        ports:
        - containerPort: 5050

